name: Build and push docker images

on:
  push:
    branches:
      - '*'
  schedule:
    - cron: '30 5 * * 3'

# Set env variables
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
  REPO_NAME: ${{secrets.REPO_NAME}}

jobs:
  build-and-push:
    runs-on: 'ubuntu-20.04'
    strategy:
      matrix:
        alpine_version: ['3.15', 'edge']
    steps:
      # https://github.com/actions/checkout
      - name: Checkout the commit triggering this job
        uses: actions/checkout@v2

      - name: Login to Docker
        run: docker login -u $DOCKER_USER -p $DOCKER_TOKEN

      - name: Build image for ${{matrix.alpine_version}}
        id: build_image
        run: |
          docker build -q -f Dockerfile.${{matrix.alpine_version}} -t $REPO_TOKEN:${{matrix.alpine_version}}-$GITHUB_SHA .

      - name: Tag image with git SHA and latest
        run: |
          docker tag $REPO_TOKEN:${{matrix.alpine_version}}-$GITHUB_SHA $DOCKER_USER/$REPO_TOKEN:${{matrix.alpine_version}}-latest
          docker tag $REPO_TOKEN:${{matrix.alpine_version}}-$GITHUB_SHA $DOCKER_USER/$REPO_TOKEN:${{matrix.alpine_version}}-$GITHUB_SHA

      - name: Push tagged images to docker
        if: ${{ (github.event_name == 'push' || github.event_name == 'pull_request') && github.ref_protected }}
        run: |
          docker push $DOCKER_USER/$REPO_TOKEN:${{matrix.alpine_version}}-$GITHUB_SHA
          docker push $DOCKER_USER/$REPO_TOKEN:${{matrix.alpine_version}}-latest
