name: Build and push docker images

on:
  push:
    branches:
      - '*'
  schedule:
    - cron: '30 5 * * 3'

# Set env variables
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
  REPO_NAME: ${{secrets.REPO_NAME}}

jobs:
  build-and-push:
    runs-on: 'ubuntu-20.04'
    strategy:
      fail-fast: false
      matrix:
        alpine_version: ['3.17', '3.18', '3.18-upstream', 'edge']
    steps:
      # https://github.com/actions/checkout
      - name: Checkout the commit triggering this job
        uses: actions/checkout@v4

      - name: Login to Docker, show env sorted variables
        run: |
          echo $DOCKER_TOKEN | docker login -u $DOCKER_USER --password-stdin
          # ACTIONS_RUNTIME_TOKEN, ACTIONS_RUNTIME_URL should be exposed
          env | sort

      - name: Build image for ${{matrix.alpine_version}}, tagging with git SHA and latest
        id: build_image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build \
          -f Dockerfile.${{matrix.alpine_version}} \
          -t ${DOCKER_USER}/$REPO_NAME:${{matrix.alpine_version}}-${GITHUB_SHA} \
          -t ${DOCKER_USER}/$REPO_NAME:${{matrix.alpine_version}}-latest \
          -t ${DOCKER_USER}/$REPO_NAME:${{matrix.alpine_version}} \
          --cache-from=type=gha \
          --cache-to=type=gha,mode=max \
          .

      - name: Push tagged images to docker
        if: ${{ (github.event_name == 'push' || github.event_name == 'pull_request') && github.ref_protected }}
        run: |
          docker push ${DOCKER_USER}/${REPO_NAME}:${{matrix.alpine_version}}-${GITHUB_SHA}
          docker push ${DOCKER_USER}/${REPO_NAME}:${{matrix.alpine_version}}-latest
          docker push ${DOCKER_USER}/${REPO_NAME}:${{matrix.alpine_version}}
