name: Build and push docker images

on:
  push:
    branches:
      - '*'
  schedule:
    - cron: '30 5 * * 3'

# Set env variables
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
  REPO_NAME: ${{secrets.REPO_NAME}}

jobs:
  build-and-push:
    runs-on: 'ubuntu-20.04'
    strategy:
      matrix:
        fail-fast: false
        alpine_version: ['3.17', '3.18', '3.18-upstream', 'edge']
    steps:
      # https://github.com/actions/checkout
      - name: Checkout the commit triggering this job
        uses: actions/checkout@v4

      - name: Login to Docker
        run: echo $DOCKER_TOKEN | docker login -u $DOCKER_USER --password-stdin

      - name: Build image for ${{matrix.alpine_version}}
        id: build_image
        run: |
          docker build -q -f Dockerfile.${{matrix.alpine_version}} -t ${DOCKER_USER}/$REPO_NAME:${{matrix.alpine_version}}-$GITHUB_SHA .
        env:
          DOCKER_BUILDKIT: 1

      - name: Tag image with git SHA and latest
        run: |
          docker tag ${DOCKER_USER}/$REPO_NAME:${{matrix.alpine_version}}-$GITHUB_SHA $DOCKER_USER/$REPO_NAME:${{matrix.alpine_version}}-latest
          docker tag ${DOCKER_USER}/$REPO_NAME:${{matrix.alpine_version}}-$GITHUB_SHA $DOCKER_USER/$REPO_NAME:${{matrix.alpine_version}}

      - name: Push tagged images to docker
        if: ${{ (github.event_name == 'push' || github.event_name == 'pull_request') && github.ref_protected }}
        run: |
          docker push $DOCKER_USER/$REPO_NAME:${{matrix.alpine_version}}-$GITHUB_SHA
          docker push $DOCKER_USER/$REPO_NAME:${{matrix.alpine_version}}-latest
          docker push $DOCKER_USER/$REPO_NAME:${{matrix.alpine_version}}
